module.exports = {
    LIBRARY_NAME: 'PrimeNG',
    LIBRARY_DESCRIPTION: 'an Angular UI component library',

    COMPONENTS: `The library includes these components (identify from issue content):
- Data: DataTable, TreeTable, VirtualScroller, Paginator, OrderList, PickList, Timeline
- Form: AutoComplete, Dropdown, MultiSelect, Calendar, InputText, InputNumber, InputMask, Password, Checkbox, RadioButton, InputSwitch, Slider, SelectButton, ToggleButton, Rating, ColorPicker, Chips, Editor, Listbox, CascadeSelect, TreeSelect
- Button: Button, SplitButton, SpeedDial
- Panel: Accordion, Card, Divider, Fieldset, Panel, TabView, Splitter, ScrollPanel, Toolbar
- Overlay: Dialog, Sidebar, ConfirmDialog, ConfirmPopup, OverlayPanel, Tooltip, DynamicDialog
- File: FileUpload
- Menu: Menu, Menubar, ContextMenu, TieredMenu, MegaMenu, PanelMenu, Steps, TabMenu, Breadcrumb, Dock
- Chart: Chart
- Messages: Toast, Messages, ConfirmationService
- Media: Carousel, Galleria, Image
- DragDrop: Drag and Drop utilities
- Misc: Avatar, Badge, BlockUI, Chip, Inplace, ProgressBar, ProgressSpinner, ScrollTop, Skeleton, Tag, Terminal, FocusTrap, Ripple, StyleClass, Animate, Defer`,

    LIBRARY_CONTEXT: `- Angular component library using TypeScript
- Uses OnPush change detection strategy
- Components should be accessible (WCAG compliant)
- Follows Angular style guide
- Uses RxJS for reactive patterns`,

    GENERATED_FILES: `- llms.txt, llms-full.txt - Generated from component documentation
- package-lock.json - Generated by npm
- *.d.ts files in dist/ - Generated TypeScript declarations
- Any file in dist/, build/, or output folders
- CHANGELOG.md - Often auto-generated`,

    CUSTOM_LABELS: `- "Angular Universal" - Server-side rendering issues`,

    PRIORITY_KEYWORDS: `- memory leak
- crash
- data loss
- security / vulnerability / XSS / injection
- regression
- breaking change
- production issue
- critical / blocker
- completely broken / unusable
- infinite loop / stack overflow / out of memory
- authentication / authorization issue`,

    DISCORD_URL: 'https://discord.gg/gzKFYnpmCY',
    DISCUSSIONS_URL: 'https://github.com/primefaces/discussions'
};
